### ISSUE TITLE
NoSuchMethodError on NoopDiscoveryClientAutoConfiguration with port in use conflict

### ISSUE THREAD

**Issue by springframeworkguru** [spring-cloud/spring-cloud-security#116]
I'm in the process of upgrading a Spring Boot project to use Spring Boot 2 / Spring 5 and ran into this confusing error below.

After a few hours of looking at dependencies, thinking I had something off. Turns out, I only had another Spring Boot project running on 8080. 

The exception below is only thrown when 8080 is in use. Without the port conflict, things start normally. 

Definitely a mistake on my part. BUT the nature of exception is confusing.

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.client.discovery.noop.NoopDiscoveryClientAutoConfiguration': Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainer()Lorg/springframework/boot/context/embedded/EmbeddedServletContainer;
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137) ~[spring-beans-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409) ~[spring-beans-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1640) ~[spring-beans-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:569) ~[spring-beans-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
```

Here is a gradle build to recreate: 

```
buildscript {
	ext {
		springBootVersion = '2.0.0.BUILD-SNAPSHOT'
	}
	repositories {
		mavenCentral()
		maven { url "https://repo.spring.io/snapshot" }
		maven { url "https://repo.spring.io/milestone" }
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'

jar {
	baseName = 'demo'
	version = '0.0.1-SNAPSHOT'
}

sourceCompatibility = 1.8

repositories {
	mavenCentral()
	maven { url "https://repo.spring.io/snapshot" }
	maven { url "https://repo.spring.io/milestone" }
}


dependencies {
	compile('org.springframework.boot:spring-boot-starter-actuator')
	compile('org.springframework.boot:spring-boot-actuator-docs')
	compile('org.springframework.boot:spring-boot-starter-cache')
//comment on this dep, and port confilct error will show normally
	compile('org.springframework.cloud:spring-cloud-starter-oauth2')

	compile('org.springframework.boot:spring-boot-starter-data-jpa')
	compile('org.springframework.boot:spring-boot-starter-data-rest')
	compile('org.springframework.boot:spring-boot-starter-integration')
	compile('org.springframework.boot:spring-boot-starter-security')
	compile('org.springframework.boot:spring-boot-starter-thymeleaf')
	compile('org.springframework.boot:spring-boot-starter-web')
	runtime('org.springframework.boot:spring-boot-devtools')
	runtime('com.h2database:h2')
	runtime('mysql:mysql-connector-java')
	testCompile('org.springframework.boot:spring-boot-starter-test')
	testCompile('org.springframework.restdocs:spring-restdocs-mockmvc')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:Dalston.BUILD-SNAPSHOT"
	}
}
```

**Comment by spencergibb** [comment]
We don't currently have boot 2.0/spring 5 support

**Comment by springframeworkguru** [comment]
Thanks Spencer - I just verified this does not happen with Spring Boot 1.5.

**Comment by springframeworkguru** [comment]
fyi - I think this is the breaking change from Spring Boot - https://github.com/spring-projects/spring-boot/commit/8619d6a2299d1656397d7657744e4d5d93ad77e4

**Comment by spencergibb** [comment]
Closing this due to inactivity. Please re-open if there's more to discuss.
