### ISSUE TITLE
JWT relay between ResourceServers not using @EnableOAuth2Client

### ISSUE THREAD

**Issue by timtebeek** [spring-cloud/spring-cloud-security#132]
Pre-Dalston.SR2 I could use the following `@FeignClient(..., configuration = TokenForwardClientConfig.class)` with
```
class TokenForwardClientConfig {
	@Bean @Autowired
	public OAuth2FeignRequestInterceptor requestInterceptor(
		OAuth2ClientContext context, OAuth2ProtectedResourceDetails resource) {
		return new OAuth2FeignRequestInterceptor(context, resource);
	}
}
```
This worked fine in my case to forward my JWTs (decoded through `security.oauth2.resource.jwt.key-uri`) from one `ResourceServer` to another.

After upgrading to Dalston.SR2/3 my resource servers no longer get an `OAuth2ClientContext` / `OAuth2ProtectedResourceDetails`, so the services failed to startup. The `OAuth2ClientContext` used to come from `OAuth2RestOperationsConfiguration$RequestScopedConfiguration` it appears; This is fine however; I can see why I maybe should not have gotten an OAuth2ClientContext in the first place, and have adapted my code to do without.

Looking for alternatives I came across [ResourceServerTokenRelayAutoConfiguration](https://github.com/spring-cloud/spring-cloud-security/blob/master/spring-cloud-security/src/main/java/org/springframework/cloud/security/oauth2/client/ResourceServerTokenRelayAutoConfiguration.java) and [AccessTokenContextRelay](https://github.com/spring-cloud/spring-cloud-security/blob/master/spring-cloud-security/src/main/java/org/springframework/cloud/security/oauth2/client/AccessTokenContextRelay.java). These however seem to require that my resource servers use `@EnableOAuth2Client` [as per the documentation on token relay](http://cloud.spring.io/spring-cloud-security/spring-cloud-security.html). (I'm not using `UserInfoTokenServices`; my resource servers decode their tokens using a JWT key downloaded on startup as detailed above.)

I don't quite get why JWT relay would only be supported in the presence of an `OAuth2ClientContext`, especially since the implementation of `AccessTokenContextRelay` seems to fall back on the `SecurityContextHolder` to get the access token if needed. I assume this ought to work fine without a managed `OAuth2ClientContext` and the required associated oauth2 client details? That would allow resource servers to pass along tokens more easily without adding a client for each.

In the meantime I've taken to relaying my JWTs using the following:
```
// No @Configuration, as that would inject this interceptor in any @FeignClient; Use (configuration=...) on each FeignClient
public class TokenForwardClientConfig {
	@Bean
	@SuppressWarnings("static-method")
	public RequestInterceptor requestInterceptor() {
		return template -> {
			Authentication auth = SecurityContextHolder.getContext().getAuthentication();
			if (auth != null) {
				Object details = auth.getDetails();
				if (details instanceof OAuth2AuthenticationDetails) {
					OAuth2AuthenticationDetails holder = (OAuth2AuthenticationDetails) details;
					template.header(HttpHeaders.AUTHORIZATION, holder.getTokenType() + " " + holder.getTokenValue());
				}
			}
		};
	}
}
```

Could someone explain to me if this is the best approach, and/or what other options there are? I'd think JWT relay between resource servers wouldn't be so uncommon as to require the above config class and a custom `configuration` attribute on every `@FeignClient`. Am I missing something?

**Comment by MadeInChina** [comment]
I have two services
 >account-service
 >auth-service

when i create a user 
account-service->auth-service.createUser()

it's working fine when using InMemoryTokenStore

but it's got exception after using JwtTokenStore.

```
2018-06-07 05:25:50.695 DEBUG [auth-service,ffc1469690976042,aee5aeb2c0d0c95f,true] 1 --- [nio-5000-exec-4] o.s.s.web.util.matcher.OrRequestMatcher  : Trying to match using Ant [pattern='/logout', DELETE]
2018-06-07 05:25:50.695 DEBUG [auth-service,ffc1469690976042,aee5aeb2c0d0c95f,true] 1 --- [nio-5000-exec-4] o.s.s.w.u.matcher.AntPathRequestMatcher  : Request 'POST /users' doesn't match 'DELETE /logout
2018-06-07 05:25:50.695 DEBUG [auth-service,ffc1469690976042,aee5aeb2c0d0c95f,true] 1 --- [nio-5000-exec-4] o.s.s.web.util.matcher.OrRequestMatcher  : No matches found
2018-06-07 05:25:50.695 DEBUG [auth-service,ffc1469690976042,aee5aeb2c0d0c95f,true] 1 --- [nio-5000-exec-4] o.s.security.web.FilterChainProxy        : /users at position 5 of 11 in additional filter chain; firing Filter: 'OAuth2AuthenticationProcessingFilter'
2018-06-07 05:25:50.695 DEBUG [auth-service,ffc1469690976042,aee5aeb2c0d0c95f,true] 1 --- [nio-5000-exec-4] p.a.OAuth2AuthenticationProcessingFilter : Authentication request failed: error="invalid_token", error_description="Cannot convert access token to JSON"
2018-06-07 05:25:50.695 DEBUG [auth-service,ffc1469690976042,aee5aeb2c0d0c95f,true] 1 --- [nio-5000-exec-4] o.s.b.a.audit.listener.AuditListener     : AuditEvent [timestamp=2018-06-07T05:25:50.695Z, principal=access-token, type=AUTHENTICATION_FAILURE, data={type=org.springframework.security.authentication.BadCredentialsException, message=Cannot convert access token to JSON}]
2018-06-07 05:25:50.696 DEBUG [auth-service,ffc1469690976042,aee5aeb2c0d0c95f,true] 1 --- [nio-5000-exec-4] o.s.s.w.header.writers.HstsHeaderWriter  : Not injecting HSTS header since it did not match the requestMatcher org.springframework.security.web.header.writers.HstsHeaderWriter$SecureRequestMatcher@33bc882d
2018-06-07 05:25:50.697 DEBUG [auth-service,ffc1469690976042,aee5aeb2c0d0c95f,true] 1 --- [nio-5000-exec-4] s.s.o.p.e.DefaultOAuth2ExceptionRenderer : Written [error="invalid_token", error_description="Cannot convert access token to JSON"] as "application/json;charset=UTF-8" using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@36c44538]
2018-06-07 05:25:50.697 DEBUG [auth-service,ffc1469690976042,aee5aeb2c0d0c95f,true] 1 --- [nio-5000-exec-4] s.s.w.c.SecurityContextPersistenceFilter : SecurityContextHolder now cleared, as request processing completed
2018-06-07 05:25:50.697 DEBUG [auth-service,ffc1469690976042,aee5aeb2c0d0c95f,true] 1 --- [nio-5000-exec-4] o.s.b.w.s.f.OrderedRequestContextFilter  : Cleared thread-bound request context: org.apache.catalina.connector.RequestFacade@7c2a44b7
2018-06-07 05:25:50.698 DEBUG [auth-service,,,] 1 --- [nio-5000-exec-4] o.a.tomcat.util.net.SocketWrapperBase    : Socket: [org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper@40a11c75:org.apache.tomcat.util.net.NioChannel@3e8f50bc:java.nio.channels.SocketChannel[connected local=/10.42.217.26:5000 remote=/10.42.140.58:54402]], Read from buffer: [0]
2018-06-07 05:25:50.699 DEBUG [auth-service,,,] 1 --- [nio-5000-exec-4] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header

java.io.EOFException: null
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.fillReadBuffer(NioEndpoint.java:1259) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.read(NioEndpoint.java:1193) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.coyote.http11.Http11InputBuffer.fill(Http11InputBuffer.java:725) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:368) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:687) ~[tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]

```

**Comment by MadeInChina** [comment]
fixed by 
```
 @Override
  public void configure(AuthorizationServerEndpointsConfigurer endpoints) {
    endpoints
        .tokenStore(tokenStore())
        .accessTokenConverter(accessTokenConverter())
        .authenticationManager(authenticationManager)
        .userDetailsService(userDetailsService);
  }
```

**Comment by gdubya** [comment]
@timtebeek sorry to resurrect a dead thread, but it looks like this was closed before you got an answer. Did you get an answer? i have the same question now.

**Comment by timtebeek** [comment]
@gdubya I've since moved on, but suspect that my work around at the bottom of my question still works. Although there's been quite some code changes since, so there might be a better way to achieve the same by now. Please let me know if you find another way.

**Comment by gdubya** [comment]
@timtebeek Thanks, yes the workaround did work. Like you said, things are changing fast so if anyone finds an answer in the future then let us know. 

For anyone's future reference, I also adjusted the RequestInterceptor to work with Keycloak (used in our case):
```
    @Bean
    public RequestInterceptor requestInterceptor() {
        return template -> {
            Authentication auth = SecurityContextHolder.getContext().getAuthentication();
            if (auth != null) {
                Object details = auth.getDetails();
                if (details instanceof SimpleKeycloakAccount) {
                    SimpleKeycloakAccount holder = (SimpleKeycloakAccount) details;
                    AccessToken token = holder.getKeycloakSecurityContext().getToken();
                    template.header(HttpHeaders.AUTHORIZATION, token.getType() + " " + holder.getKeycloakSecurityContext().getTokenString());
                }
            }
        };
    }
```
