### ISSUE TITLE
encrypt.key-store.location=file://d:/config-srv.jks

### ISSUE THREAD

**Issue by ShZhengqin** [spring-cloud/spring-cloud-security#165]
Hi,
     I use spring-boot-starter-security 2.0.3 Finchley.RELEASE , I know the paramter: encrypt.key-store.location=classpath://config-srv.jks is right, but i want to set the encrypt.key-store.location=file://d:/config-srv.jks, because i do not want to put the jks file into the source code, so i need to put the jks file into the directory outside source code, for example: d dish。
    when i set encrypt.key-store.location=file://d:/config-srv.jks,  my project run error:  
```
Caused by: java.lang.IllegalStateException: Cannot load keys from store: URL [file://d:/config-srv.jks]
	at org.springframework.security.rsa.crypto.KeyStoreKeyFactory.getKeyPair(KeyStoreKeyFactory.java:64) ~[spring-security-rsa-1.0.5.RELEASE.jar:na]
	at org.springframework.cloud.config.server.encryption.KeyStoreTextEncryptorLocator.locate(KeyStoreTextEncryptorLocator.java:84) ~[spring-cloud-config-server-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.cloud.config.server.encryption.LocatorTextEncryptor.decrypt(LocatorTextEncryptor.java:52) ~[spring-cloud-config-server-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.cloud.bootstrap.encrypt.EnvironmentDecryptApplicationInitializer.decrypt(EnvironmentDecryptApplicationInitializer.java:194) ~[spring-cloud-context-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	... 9 common frames omitted
Caused by: java.net.UnknownHostException: d
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_161]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_161]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_161]
	at sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:962) ~[na:1.8.0_161]
	at sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:924) ~[na:1.8.0_161]
	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1019) ~[na:1.8.0_161]
	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1005) ~[na:1.8.0_161]
	at sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:294) ~[na:1.8.0_161]
	at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:400) ~[na:1.8.0_161]
	at org.springframework.core.io.UrlResource.getInputStream(UrlResource.java:171) ~[spring-core-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.security.rsa.crypto.KeyStoreKeyFactory.getKeyPair(KeyStoreKeyFactory.java:53) ~[spring-security-rsa-1.0.5.RELEASE.jar:na]
	... 12 common frames omitted
```

**Comment by ryanjbaxter** [comment]
This certainly is not a problem with spring-cloud-security and I dont think Spring Cloud is involved either.  It sounds like your path is not constructed correctly.  Also try without Spring Cloud on the classpath and see if you still have a problem.  If the problem only occurs with Spring Cloud on the classpath please open an issue in spring-cloud-commons.
