### ISSUE TITLE
Apparent bean wiring paradox in `@ConfigurationProperties` objects for SSO

### ISSUE THREAD

**Issue by jghiloni** [spring-cloud/spring-cloud-security#47]
We've built a library to use spring-cloud-security to provide SSO to our developers behind an abstraction layer (in case, for example, the powers that be decide they don't want to use OAuth2). I upgraded the dependencies yesterday from 1.0.0.M3 to 1.0.0.RELEASE and now I'm seeing quite the odd paradox in one situation.

When I try to start my app, which has `@EnableResourceServer` present, I get an exception that `ResourceServerProperties.Jwt.keyUri` is null, even though I can see in the logs that it's being loaded from my properties file. When I add `@EnableConfigurationProperties({ResourceServerProperties.class})` to one of my configuration classes to enable the bean, I then get an error that it can't create the bean, because it's missing a constructor argument of type String.

Exception when `@EnableConfigurationProperties` is missing:
```
2015-03-12T10:12:03.09-0600 [App/0]   OUT Caused by: java.lang.IllegalArgumentException: 'uriTemplate' must not be null
2015-03-12T10:12:03.09-0600 [App/0]   OUT       at org.springframework.util.Assert.hasText(Assert.java:162)
2015-03-12T10:12:03.09-0600 [App/0]   OUT       at org.springframework.web.util.UriTemplate$Parser.<init>(UriTemplate.java:179)
2015-03-12T10:12:03.09-0600 [App/0]   OUT       at org.springframework.web.util.UriTemplate$Parser.<init>(UriTemplate.java:172)
2015-03-12T10:12:03.09-0600 [App/0]   OUT       at org.springframework.web.util.UriTemplate.<init>(UriTemplate.java:65)
2015-03-12T10:12:03.09-0600 [App/0]   OUT       at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:528)
2015-03-12T10:12:03.09-0600 [App/0]   OUT       at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:236)
2015-03-12T10:12:03.09-0600 [App/0]   OUT       at org.springframework.cloud.security.oauth2.resource.ResourceServerTokenServicesConfiguration$JwtTokenServicesConfiguration.jwtTokenEnhancer(ResourceServerTokenServicesConfiguration.java:247)
2015-03-12T10:12:03.09-0600 [App/0]   OUT       at org.springframework.cloud.security.oauth2.resource.ResourceServerTokenServicesConfiguration$JwtTokenServicesConfiguration$$EnhancerBySpringCGLIB$$6c1b5783.CGLIB$jwtTokenEnhancer$2(<generated>)
2015-03-12T10:12:03.09-0600 [App/0]   OUT       at org.springframework.cloud.security.oauth2.resource.ResourceServerTokenServicesConfiguration$JwtTokenServicesConfiguration$$EnhancerBySpringCGLIB$$6c1b5783$$FastClassBySpringCGLIB$$d4ad3e27.invoke(<generated>)
2015-03-12T10:12:03.09-0600 [App/0]   OUT       at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
2015-03-12T10:12:03.09-0600 [App/0]   OUT       at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:309)
2015-03-12T10:12:03.09-0600 [App/0]   OUT       at org.springframework.cloud.security.oauth2.resource.ResourceServerTokenServicesConfiguration$JwtTokenServicesConfiguration$$EnhancerBySpringCGLIB$$6c1b5783.jwtTokenEnhancer(<generated>)
2015-03-12T10:12:03.09-0600 [App/0]   OUT       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2015-03-12T10:12:03.09-0600 [App/0]   OUT       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2015-03-12T10:12:03.09-0600 [App/0]   OUT       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-03-12T10:12:03.09-0600 [App/0]   OUT       at java.lang.reflect.Method.invoke(Method.java:483)
2015-03-12T10:12:03.09-0600 [App/0]   OUT       at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
2015-03-12T10:12:03.09-0600 [App/0]   OUT       ... 91 more
```

Exception when `@EnableConfigurationProperties` is present:
```
2015-03-12T10:07:43.99-0600 [App/0]   OUT Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cloud.security.oauth2.resource.ResourceServerTokenServicesConfiguration$JwtTokenServicesConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.cloud.security.oauth2.resource.ResourceServerProperties org.springframework.cloud.security.oauth2.resource.ResourceServerTokenServicesConfiguration$JwtTokenServicesConfiguration.resource; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'spring.oauth2.resource.CONFIGURATION_PROPERTIES': Unsatisfied dependency expressed through constructor argument with index 0 of type [java.lang.String]: : No qualifying bean of type [java.lang.String] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [java.lang.String] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1202)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:368)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1111)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1006)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
2015-03-12T10:07:43.99-0600 [App/0]   OUT   ... 56 more
```

Any thoughts on what changed between M3 and RELEASE that could have caused this? Thanks!

**Comment by jghiloni** [comment]
Figures, I open an issue and almost immediately find the answer. It seems just doing `@EnableConfigurationProperties` (without any arguments) solves the problem.
