### ISSUE TITLE
java.lang.IllegalStateException: Cannot deserialize BeanFactory with @EnableRedisHttpSession with spring-boot-starter & spring-cloud-starter

### ISSUE THREAD

**Issue by chdanish** [spring-cloud/spring-cloud-security#91]
Getting below exception when using **@EnableRedisHttpSession** with spring-boot-starter (1.3.2) & spring-cloud-starter (Brixton.M3) & neo4j (4.0.0.RELEASE)

neo config is 

```
<package so.pickme.replica.config;

import org.neo4j.ogm.session.Session;
import org.neo4j.ogm.session.SessionFactory;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Scope;
import org.springframework.context.annotation.ScopedProxyMode;
import org.springframework.data.neo4j.repository.config.EnableNeo4jRepositories;
import org.springframework.data.neo4j.config.Neo4jConfiguration;
import org.springframework.data.neo4j.server.Neo4jServer;
import org.springframework.data.neo4j.server.RemoteServer;
import org.springframework.transaction.annotation.EnableTransactionManagement;

@Configuration
@EnableNeo4jRepositories("so.pickme.repository")
/*@EnableTransactionManagement*/
public class NeoConfig extends Neo4jConfiguration {

    //public static final int NEO4J_PORT = 7474;

    @Override
    public SessionFactory getSessionFactory() {
        return new SessionFactory("so.pickme.replica.domain");
    }

    @Bean
    public Neo4jServer neo4jServer() {
        return new RemoteServer("http://neo4j-pickme.rhcloud.com","neo4j", "neo4j2319");
    }

    @Override
    @Bean
    @Scope(value = "session", proxyMode = ScopedProxyMode.TARGET_CLASS)
    public Session getSession() throws Exception {
        return super.getSession();
    }
}>
```

Auth server:

```
@SpringBootApplication
@EnableRedisHttpSession
@SessionAttributes("authorizationRequest")
@Controller
@ComponentScan({ "so.pickme" })
@ImportResource({"classpath:trace-context.xml"})
@EnableResourceServer
@EnableAutoConfiguration
public class AuthserverApplication extends WebMvcConfigurerAdapter {
	

	
	@Primary
	@Bean
	@Scope("session")
	public StringRedisTemplate redisTemplate() {
	    StringRedisTemplate template = new StringRedisTemplate(redisConnectionFactory());
	    // explicitly enable transaction support
	    template.setEnableTransactionSupport(true);
	    template.setEnableDefaultSerializer(false);
	    
	    return template;
	  }
	@Bean
    public RedisConnectionFactory redisConnectionFactory() {
        JedisConnectionFactory jedisConnectionFactory = new JedisConnectionFactory();
        jedisConnectionFactory.setHostName("localhost");
        jedisConnectionFactory.setPort(6379);
        jedisConnectionFactory.setUsePool(true);
        return jedisConnectionFactory;
    }
	
	@Bean
	public TomcatEmbeddedServletContainerFactory tomcatEmbeddedServletContainerFactory() {
	    return new TomcatEmbeddedServletContainerFactory();
	} ....
```

Exception with startup log:

```
17:03:09.155 [http-nio-9998-exec-1] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/uaa] threw exception
org.springframework.data.redis.serializer.SerializationException: Cannot deserialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is java.lang.IllegalStateException: Cannot deserialize BeanFactory with id 8fd3f3e8-e0a1-3445-8ebd-f3f3ac549152: no factory registered for this id
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:41) ~[spring-data-redis-1.6.2.RELEASE.jar:1.6.2.RELEASE]
	at org.springframework.data.redis.core.AbstractOperations.deserializeHashValue(AbstractOperations.java:316) ~[spring-data-redis-1.6.2.RELEASE.jar:1.6.2.RELEASE]
	at org.springframework.data.redis.core.AbstractOperations.deserializeHashMap(AbstractOperations.java:277) ~[spring-data-redis-1.6.2.RELEASE.jar:1.6.2.RELEASE]
	at org.springframework.data.redis.core.DefaultHashOperations.entries(DefaultHashOperations.java:227) ~[spring-data-redis-1.6.2.RELEASE.jar:1.6.2.RELEASE]
	at org.springframework.data.redis.core.DefaultBoundHashOperations.entries(DefaultBoundHashOperations.java:101) ~[spring-data-redis-1.6.2.RELEASE.jar:1.6.2.RELEASE]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.getSession(RedisOperationsSessionRepository.java:233) ~[spring-session-1.0.0.RELEASE.jar:na]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.getSession(RedisOperationsSessionRepository.java:220) ~[spring-session-1.0.0.RELEASE.jar:na]
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.getSession(RedisOperationsSessionRepository.java:141) ~[spring-session-1.0.0.RELEASE.jar:na]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.getSession(SessionRepositoryFilter.java:190) ~[spring-session-1.0.0.RELEASE.jar:na]
	at org.springframework.web.context.request.ServletRequestAttributes.updateAccessedSessionAttributes(ServletRequestAttributes.java:255) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.context.request.AbstractRequestAttributes.requestCompleted(AbstractRequestAttributes.java:48) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:106) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:111) ~[spring-session-1.0.0.RELEASE.jar:na]
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:65) ~[spring-session-1.0.0.RELEASE.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:103) ~[spring-boot-actuator-1.3.2.RELEASE.jar:1.3.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) ~[tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:521) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_40]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_40]
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is java.lang.IllegalStateException: Cannot deserialize BeanFactory with id 8fd3f3e8-e0a1-3445-8ebd-f3f3ac549152: no factory registered for this id
	at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:78) ~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:36) ~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:39) ~[spring-data-redis-1.6.2.RELEASE.jar:1.6.2.RELEASE]
	... 49 common frames omitted
Caused by: java.lang.IllegalStateException: Cannot deserialize BeanFactory with id 8fd3f3e8-e0a1-3445-8ebd-f3f3ac549152: no factory registered for this id
	at org.springframework.beans.factory.support.DefaultListableBeanFactory$SerializedBeanFactoryReference.readResolve(DefaultListableBeanFactory.java:1428) ~[spring-beans-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectStreamClass.invokeReadResolve(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readObject0(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.defaultReadFields(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readSerialData(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readObject0(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.defaultReadFields(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readSerialData(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readObject0(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.defaultReadFields(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readSerialData(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readObject0(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readArray(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readObject0(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.defaultReadFields(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.defaultReadObject(Unknown Source) ~[na:1.8.0_40]
	at org.springframework.aop.framework.AdvisedSupport.readObject(AdvisedSupport.java:557) ~[spring-aop-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectStreamClass.invokeReadObject(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readSerialData(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readObject0(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.defaultReadFields(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readSerialData(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readObject0(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.defaultReadFields(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readSerialData(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readObject0(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.defaultReadFields(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readSerialData(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readObject0(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.defaultReadFields(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readSerialData(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readObject0(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.defaultReadFields(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readSerialData(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readObject0(Unknown Source) ~[na:1.8.0_40]
	at java.io.ObjectInputStream.readObject(Unknown Source) ~[na:1.8.0_40]
	at org.springframework.core.serializer.DefaultDeserializer.deserialize(DefaultDeserializer.java:70) ~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	at org.springframework.core.serializer.support.DeserializingConverter.convert(DeserializingConverter.java:73) ~[spring-core-4.2.4.RELEASE.jar:4.2.4.RELEASE]
	... 51 common frames omitted
```

**Comment by dsyer** [comment]
Duplicates https://github.com/spring-cloud/spring-cloud-commons/issues/93
