### ISSUE TITLE
Spring cloud security not working with Spring cloud Brixton SR2

### ISSUE THREAD

**Issue by kakawait** [spring-cloud/spring-cloud-security#97]
Saw on *gitter* https://gitter.im/spring-cloud/spring-cloud?at=577b783ff06cda5d098be1cb

When using `Zuul` with `@EnableOauth2Sso` with `org.springframework.cloud:spring-cloud-dependencies:Brixton.SR2` 

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.security.oauth2.proxy.AuthenticationHeaderFilter]: Factory method 'authenticationHeaderFilter' threw exception; nested exception is java.lang.NoSuchMethodError: org.springframework.cloud.netflix.zuul.filters.ProxyRequestHelper.setTraces(Lorg/springframework/boot/actuate/trace/TraceRepository;)V
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
    ... 49 common frames omitted
Caused by: java.lang.NoSuchMethodError: org.springframework.cloud.netflix.zuul.filters.ProxyRequestHelper.setTraces(Lorg/springframework/boot/actuate/trace/TraceRepository;)V
    at org.springframework.cloud.security.oauth2.proxy.OAuth2ProxyAutoConfiguration$AuthenticationHeaderFilterConfiguration.authenticationHeaderFilter(OAuth2ProxyAutoConfiguration.java:79) ~[spring-cloud-security-1.1.0.RELEASE.jar:1.1.0.RELEASE]
    at org.springframework.cloud.security.oauth2.proxy.OAuth2ProxyAutoConfiguration$AuthenticationHeaderFilterConfiguration$$EnhancerBySpringCGLIB$$26c27b3b.CGLIB$authenticationHeaderFilter$0(<generated>) ~[spring-cloud-security-1.1.0.RELEASE.jar:1.1.0.RELEASE]
    at org.springframework.cloud.security.oauth2.proxy.OAuth2ProxyAutoConfiguration$AuthenticationHeaderFilterConfiguration$$EnhancerBySpringCGLIB$$26c27b3b$$FastClassBySpringCGLIB$$f6d0f2f8.invoke(<generated>) ~[spring-cloud-security-1.1.0.RELEASE.jar:1.1.0.RELEASE]
    at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.1.RELEASE.jar:4.3.1.RELEASE]
    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356) ~[spring-context-4.3.1.RELEASE.jar:4.3.1.RELEASE]
    at org.springframework.cloud.security.oauth2.proxy.OAuth2ProxyAutoConfiguration$AuthenticationHeaderFilterConfiguration$$EnhancerBySpringCGLIB$$26c27b3b.authenticationHeaderFilter(<generated>) ~[spring-cloud-security-1.1.0.RELEASE.jar:1.1.0.RELEASE]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.1.RELEASE.jar:4.3.1.RELEASE]
    ... 50 common frames omitted
```

---

Sample to reproduce https://github.com/kakawait/scs-gh-97

**Comment by dsyer** [comment]
Fixed in f59b624.
